### ISSUE TITLE
make it so livecodelab also dozes off when the program is only made of comments (and tabs and whitespaces)

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#142]

**Comment by rumblesan** [comment]
so this should be working now. Each of the code compilers checks to see if the output that it generates is empty after code compilation. If it is then the livecodelab core will set things to sleep.

https://github.com/davidedc/livecodelab/blob/master/coffee/core/livecodelab-core.coffee#L254
https://github.com/davidedc/livecodelab/blob/master/coffee/languages/livelangv1/compiler.coffee#L39
https://github.com/davidedc/livecodelab/blob/master/coffee/languages/livelangv2/compiler.coffee#L57

Have a quick double check if you've got a moment, but I think we can close this

**Comment by davidedc** [comment]
There was a time, I don't remember when, when there was a simpler mechanism - there was (maybe there still is) a flag "somethingBeenDrawn" (or the likes) set to true wherever any drawing primitive is called.

So the animation loop would check that flag before attempting a render.

It seemed to me slightly more generic - so you could have a program doing only matrix transformations, and no render would happen...

It's not for optimisation's sake - it just seemed to me that the correct (and simpler) way to check whether to even attempt a render was to check whether anybody even called a drawing primitive...

**Comment by rumblesan** [comment]
so I think this is actually working as we want right? I don't think that the edge case of running without rendering is something we want to support is it?
