### ISSUE TITLE
make it so when the code is just comments or whitespaces or tabs then the framerate badge is not shown

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#151]

**Comment by rumblesan** [comment]
so, this a slightly interesting one, and it's currently working slightly differently between the two languages.

in both languages, if you type in any combination of white space, new lines and tabs, then the framerate/stats stuff won't show up. As soon as you type in a letter it appears. It will then stay around if you just delete all the letters/code, and will only disappear again once there's no text (including whitespace)

the difference between the two languages is that V2 won't show the stats if you type in a comment, whereas V1 will.

**Comment by davidedc** [comment]
hmmm this is linked to https://github.com/davidedc/livecodelab/issues/142#issuecomment-114506777 - ideally we want to enable the badge only when rendering, and ideally based on whether any drawing primitive has been called.

**Comment by rumblesan** [comment]
so this should be fixed now I believe
