### ISSUE TITLE
make it so the user can set the fps from the program

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#152]
So it's possible to do the same that processing does with the fps() command.

look at this in animation-loop:

AnimationLoop.wantedFramesPerSecond = AnimationLoop.AS_HIGH_FPS_AS_POSSIBLE

so, basically, make a new fps command that changes that value.

**Comment by rumblesan** [comment]
Ah hah, so this is around! this ties into what I mentioned in #254
