### ISSUE TITLE
Create a Grammar and a Parser

### ISSUE THREAD

**Issue by rumblesan** [davidedc/livecodelab#182]
The current system of regexps and coffee script compiler is fine, but having our own parser would make it significantly easier to extend the language

**Comment by rumblesan** [comment]
so is this now essentially all done? we have the grammar/parser/interpreter and it's merged in.

There are some of these features that I don't think we've properly sorted, such as the <stuff> closure generation, but I think we can raise further issues for those things if need be.

**Comment by davidedc** [comment]
yes it's merged. The only caveat being that the grammar/parser/interpreter has to be turned on via parameter in the URL. I think that was in the meantime the test cases we have were running OK with both systems (which I don't think they do - there seem to be some basic tests that should be working on both systems but they don't, I think I highlighted them in either the pull requests or via email).

**Comment by rumblesan** [comment]
Closing this now, will raise more issues as needed
