### ISSUE TITLE
matrixes and geometry don't need to be moved around in "dead" frames

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#187]
"dead frames" are the frames too close to the playing of the next sample.

Still, in the "dead frames" the program is run and a bunch of matrixes and geometry is moved around (although not painted, which saves a lot of time). That doesn't need to happen, a simple flag could avoid that and hopefully make the samples playing even less laggy.

**Comment by rumblesan** [comment]
so now that the audio system has been simplified with either the web audio api or buzz, this isn't actually an issue any more is it?

**Comment by rumblesan** [comment]
going to close this as after having a look it's not an issue any more. the animation loop is totally separate from the audio triggering now.
