### ISSUE TITLE
Safari 6 revamps Web Audio API - check whether you can avoid preloading sound

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#20]
...right now in Safari all sounds are preloaded. Which means that the time-to-launch time is quite long and loads of memory is used (and never released by the way, Safari tends to leak memory).

If the new Web Audio API implementation works like in Chrome, then maybe sounds can be loaded dynamically just like in Chrome?

**Comment by rumblesan** [comment]
if we get #241 merged then this should be sorted

**Comment by rumblesan** [comment]
think this is no longer an issue either. mentioned PR was merged and the web audio API is not generally better in all the browsers.
