### ISSUE TITLE
WebGL Warnings

### ISSUE THREAD

**Issue by noio** [davidedc/livecodelab#214]
I get a whole bunch of WebGL warnings every time I start LCL. Is there a way to either fix or mute these? They make debugging somewhat annoying. :anger: 

![screen shot 2013-12-09 at 13 21 59](https://f.cloud.github.com/assets/271730/1704527/9268aee4-60cc-11e3-9015-09f138dd2e69.png)

**Comment by rumblesan** [comment]
this is no longer happening
