### ISSUE TITLE
function "isFunction" is now defined in two files (graphics-commands and matrix-commands) and hence needs to be refactored.

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#215]
isFunction = (functionToCheck) ->
  getType = {}
  functionToCheck and getType.toString.call(functionToCheck) is "[object Function]"

**Comment by rumblesan** [comment]
so this is actually in the bigcleanup pull request. can close once PR #255 is merged

**Comment by rumblesan** [comment]
fixed now #255 is merged
