### ISSUE TITLE
Links to "Pawfal collective" ( http://www.pawfal.org/index.php?page=PawfalPeople ) need to be fixed

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#234]
(gives 404 now). There is at least one such link in the livecodelab home page, there might be more in various readmes

**Comment by rumblesan** [comment]
so I can't find any links to pawfal within the LCL code. can we close this?

**Comment by rumblesan** [comment]
closed as I'm pretty sure this isn't an issue
