### ISSUE TITLE
Grunt `connect` task serves map files, but not the source they point to.

### ISSUE THREAD

**Issue by xinaesthete** [davidedc/livecodelab#235]
I've noticed that it's necessary to disable Javascript source maps to debug effectively, as otherwise it seems that the browser tries to load the original `.coffee` source, which isn't served as it isn't under `dist`.

I have limited coffeescript experience, so I don't know how well this debugging works in general.

**Comment by rumblesan** [comment]
Fixed once the webpack build is merged
