### ISSUE TITLE
Just A Small Intro For Me

### ISSUE THREAD

**Issue by Richard-Mineall** [davidedc/livecodelab#246]
I'm Richard Layton, nice to meet you guys, I just wanted to post this where you would see it, also I wanted to address what I'm planning on doing, I can help with plenty of projects, but for right now my main focus will be to make livecodelab able to working other languages, like German and Spanish,
as well as adding in a few cool features, like a code collapsing feature, I hope you guys will like my ideas.

**Comment by rumblesan** [comment]
Hey, thanks for getting involved. I certainly welcome a fresh pair of eyes to have a look at LCL and it will probably give us another shunt to try and finish off some things heh.

Localisation is one of those things that we had originally and would be really nice to have again, and we're certainly open to anything else you can think of to improve things.

**Comment by davidedc** [comment]
Welcome Richard! Liking your videos of LCL!

I'd always suggest to flesh out the thought in a github issue dedicated to each topic, as we've been working on LCL quite a bit so we have a couple of ideas on possible paths to take.

Also, I encourage two more things: a) maintenance over new features (for example codemirror needs updating) and b) small step-by-step release.

I'm also the mercurial guardian of the LCL Master branch, which means I can scratch on a door, have it open for me, then not go outside, I can shred sofas, I can paw and break precious Ming vases, I can have people bring huge merges to me and refuse them with a cheshire cat smile :smile_cat: . You've been warned!

**Comment by Richard-Mineall** [comment]
well, I'm having some trouble with getting grunt on my computer, I have node.js and Ubuntu, my computer wants me to run npm somewhere other than node.js

**Comment by rumblesan** [comment]
so you might find it easier to look into nodenv if you're having issues

https://github.com/OiNutter/nodenv

**Comment by Richard-Mineall** [comment]
Does that replace npm, grunt, or node.js?

**Comment by Richard-Mineall** [comment]
I'm wondering if there are any triangles in livecodelab, if not they should be added

**Comment by davidedc** [comment]
closing the issue as all interested participants have been notified. Issue will remain anyways, it's just closed.
