### ISSUE TITLE
Subreddit

### ISSUE THREAD

**Issue by Richard-Mineall** [davidedc/livecodelab#247]
I was wondering if I should make A subreddit for livecodelab if there isn't one already, and this would be a good way to share codes as one person could place an image, and then paste in the codeto accompany it.

**Comment by davidedc** [comment]
sounds like a great idea, we got a couple of mentions but I don't think there is a subreddit yet.

I'm just a reader of reddit, I'm not "in the circle" so to speak, so please go ahead (and then share link!) if you are "in the know".

Cheers!

**Comment by Richard-Mineall** [comment]
Ok I'm not exactly known but still being in school allows me to point some people to the subreddit and/or the website themselves

**Comment by rumblesan** [comment]
closing this as nobody seems to have the time or inclination currently.
