### ISSUE TITLE
Remove motion blur functionality when using the canvas renderer

### ISSUE THREAD

**Issue by rumblesan** [davidedc/livecodelab#251]
There's a lot of code tied up with getting the canvas renderer to work, and a large chunk of it in the threejs-system is around motion blur.

To be honest I think that it's more hassle than it's worth and would make the threejs stuff much easier to maintain

**Comment by davidedc** [comment]
agreed

**Comment by rumblesan** [comment]
cool, I might start having a proper look see what can be removed soon

**Comment by rumblesan** [comment]
There's definitely code that can be removed, but it's too late for me to pick through it now haha

**Comment by rumblesan** [comment]
so if the decision has been made to remove the canvas renderer, then I feel like this could just be closed now
