### ISSUE TITLE
if the background is solid and fully opaque then...

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#33]
you don't need to have a situation of transparency with a solid fill below.

It can be easier, where the div below does nothing, and just the webgl context initialises the background with a solid opaque fill.

I have no idea if this is worth doing, because it might be added complication that streamlines something where there is no performance gain.

But maybe it's worth adding a comment somewhere explaining this edge case, just to say that someone thought about it.

**Comment by rumblesan** [comment]
so this feels like an unnecessary optimisation to me. I think that we should stick to transparent 3js backgrounds and then render actual backgrounds on the div/canvas beneath. can't see that this would necessarily make anything quicker tbh

**Comment by rumblesan** [comment]
After having had a look at the background code, I think that we should avoid using webgl for background fills of any kind. it makes more sense to me that we have it just handling 3d rendering, and the background colours/gradients are handled externally
