### ISSUE TITLE
implement "bigger" and "smaller"

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#51]
which is a shorthand for scale(1.1) and scale (0.9) - or some constants like that

**Comment by rumblesan** [comment]
I have no idea where that commit has ended up. github still has it, but it's not on any branch or merged in heh.

**Comment by davidedc** [comment]
I looked at the code of the commit link, let's remember to add support for chaining by passing a parameter that can be a function. there are several examples of how that's handled (e.g. noStroke). That's so we can use ```smaller box```
or ```smaller smaller box``` etc.
