### ISSUE TITLE
add a debug variable to turn on/off the window.onerror catch-all mechanism

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#7]
there is a function in livecodelab.js that catches all the errors:

```
window.onerror = function(msg, url, linenumber) { ...
```

This is great in the livecoding environment, but it's bad for when debugging the environment itself, because it prevents error from being revealed/handled by the debugger in the browser.

So there should be a quick switch to enable/disable that catch-all mechanism.

**Comment by rumblesan** [comment]
I don't think this is the case any more is it? I can't find the code anywhere.
