### ISSUE TITLE
IE 9: sound plays slower than in firefox and chrome

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#82]
test:

play 'tranceKick' ,'xzzz xzzz xzzz xzzz'

should play a regular 1hz beat. It's slightly lower frequency instead. The sample itself seems to have just the right duration and pitch.

I don't think this is a performance issue of IE9, because IE9 can be pushed to do much faster beats with multiple instruments and it plays them regularly. There probably is some subtler reason involving the semantics of timings of playing sounds or the semantics of setInterval/setTimeout.

Probably easy to first comment-out the sound-playing code and just do some printouts when the sound *should* have played and see the beat of that printout.

**Comment by rumblesan** [comment]
question about whether IE9 is actually supported again

**Comment by davidedc** [comment]
I think we should aim for "latest version of IE, Firefox, Chrome, Safari that mere mortals can install". Like, no experimental versions and no preview versions (say, Edge right now), just "the latest", nothing before it.

**Comment by rumblesan** [comment]
that works for me. it seems that webgl is fine pretty much everywhere then, except for IE10
http://caniuse.com/#search=web%20gl

and webaudio is fine everywhere except IE in general
http://caniuse.com/#search=web%20audio

for the audio stuff, buzz will handle IE, and everything else can use web audio api. for graphics, I guess the question is whether we want to support IE10 by keeping the canvas renderer in. I think it's probably worth it as it's already there

**Comment by rumblesan** [comment]
closing as we're not supporting IE9
